### PR TITLE
"info" command to show summary for license from choosealicense.com

### PR DESCRIPTION
**Pull request by ttscoff**
New license templates: artistic, bsd-simple, eclipse, no-license, unlicense
Use "licgen info [license]" to display a formatted summary

### CODE REVIEW

**Comment by ttscoff** [comment]
Of course, now I realize that this info is all in the new license API, so that was a waste of an hour...

**Comment by xiongchiamiov** [comment]
I really kinda hate choosealicense - it has such broad descriptions of licenses that miss all sorts of important things.  Those individual summaries look alright, though.

Personally, I'd go with the more mature and standardized [TLDRLegal](https://tldrlegal.com/) for summaries; it's the best one I've seen.

Although really it seems like summaries of licenses is out of the scope of this project; deciding on a license is a really complicated process (I've created [an entire wizard](https://github.com/xiongchiamiov/ossified), and even that is missing a lot), and licgen has a pretty simple featureset currently: dump a license in the current directory.

**Comment by ttscoff** [comment]
I mostly just appreciated the overview of "Required, Permitted, 
Forbidden" charts to help me narrow down the options. Yes, it's 
oversimplified, but it's a very handy tool for filtering at the 
beginning of the selection process.

Feel free to close the pull request, I won't be heartbroken :).

-Brett

**Comment by xiongchiamiov** [comment]
To be clear about things: I'm not the owner here, just another guy. :)  So what @blaix thinks is far more important.

**Comment by blaix** [comment]
> Although really it seems like summaries of licenses is out of the scope of this project; deciding on a license is a really complicated process (I've created an entire wizard, and even that is missing a lot), and licgen has a pretty simple featureset currently: dump a license in the current directory.

Bingo. If you want to submit again with just the new templates I'll pull those in. Thanks, though!

**Pull request closed without merging**
